### ISSUE TITLE
fsync issues

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#201] opened 2021-08-17 03:34 UTC
Tim Fox @purplefox mentioned the following concerns in the gitter chatroom. As I think this might be interested by other potential users as well, I've moved the discussion here so the information can be later searched & read by everyone including those who don't use the gitter chatroom. 

Tim Fox @purplefox mentioned that - 

> Hi @lni thanks for getting back to me. If Raft really requires committed log entries to be 100% durably stored then I can't see how that would work in the real world.

First of all, please note that the fsync usage issue you mentioned is not something unique in Dragonboat or Raft. I am 100% sure that all consensus libraries are doing the same. As explained earlier in Gitter, rather than betting on probabilities, consensus libraries like Dragonboat provide stricter guarantees. This helps developers to better reasoning about their systems and data, for a 3 replica Raft group, when two replicas are up and running, they would be able to know that all their data is available. If durability is not guaranteed, then they would only be able to say that their data is available with very high probability.  

The real question here is not whether Dragonboat is requiring too much guarantees on durable storages, it is really about whether you do need strongly consistent data like the one provided by Raft & Paxos. 

> In the real world disks fail, battery backed caches fail. Also, when running on Amazon EBS (most probably the most common place to run distributed systems) there's an annual failure rate of 0.1 to 0.2% per year https://docs.aws.amazon.com/whitepapers/latest/aws-storage-services-overview/durability-and-availability-3.html that means 1 in 500 of your disk volumes will fail per year. For a company with a lot of volumes (like us) that's a lot of failures every year. Any distributed systems that we build on top of that must be able to recover from failures.

Indeed. In Dragonboat, we consider failure as a feature of life, not some exceptional events. That is why we need to make sure that no data is lost when the majority quorum is available after such failures. Requiring fsync() to do what the posix requires it to do is one of the basic requirement to realize that goal. 

> As I mentioned before, when using something like Amazon EBS, how do you think it gets fsync speeds of a few ms? EBS is a SAN, so it basically replicates writes to multiple replicas and writes into page cache on each replica. When you call fsync it does not actually fsync that data to the disks on the replicas. It's sufficient for EBS to just replicate in memory and fsync asynchronously in order to comply with the advertised failure rate of 0.1 to 0.2% per year of dataloss. It's all about mathematical probabilities!  (These can be worked out quite easily if you know mean time between failures of the replicas). This is how clouds storage works! Performance would be terrible if they actually fsynced every time you called fsync.

Modern SSDs can deliver fsync latencies of a few dozen microseconds, with that in mind, EBS's a few millisecond fsync delays is pretty reasonable to me as in theory they can always attach some SSDs to regular block storages backed by HDDs to just handle fsync data.

**Please also note that Dragonboat is not requiring you to use EBS or any cloud services. Being able to durably store data is what it requires.** When using Amazon EC2 nodes, surely you can choose to store such durably data on instance store volumes or something similar. 

>  So, even if dragonboat fsyncs on each raft batch then there's no guarantee they are stored durably, and it's impossible for dragonboat to provide a lower failure rate than the one guaranteed by the underlying storage system (e.g. EBS).

Please check the posix manpage on fsync(), it states that - 

> fsync() transfers ("flushes") all modified in-core data of (i.e.,
       modified buffer cache pages for) the file referred to by the file
       descriptor fd to the disk device (or other permanent storage
       device) **so that all changed information can be retrieved even if
       the system crashes or is rebooted.**

https://man7.org/linux/man-pages/man2/fsync.2.html

If the storage system refuses to be compatible with such well known & defined standards, then all belts are off and you are on your own. 

> In order for dataloss to occur in a replicated system all replicas need to fail at the same time, and then all unsynced data in those replicas will be lost. This is a very unlikely event and the probability can be calculated from the statistics you gather on cloud about machine failures and also if you know the mean time between asynchronous syncs. In many cases the probability of this occurring leads to a failure rate of less than the EBS advertised failure rate! So, and here is the important point - there is absolutely no point in fsyncing any more as the chance of underlying storage system failure (EBS) is already higher than the chance of dataloss at our level. Again, it's all about probabilities.

It is never about how low is the probability. For the guarantees provided by Raft & Paxos, **losing data should never happen** when the majority of nodes are available after such repeated reboots. If your system doesn't want such strong guarantee, please feel free to choose from weaker protocols. 

> What's the worst that can happen if the raft log is not fsynced for every committed record? We assume the underlying log store (e.g. Pebble or RocksDB) does not become corrupt in the case of a sudden machine failure, and this is a good assumption for both Pebble or RocksDB - when they restart after power failure, records may be missing from the end of the log but the log will not be corrupt.

It will lead to total violation of linearizability, which is the single most important feature provided by Raft & Paxos. 

> If a Raft replica fails after power loss and has lost some records from the end of it's committed raft log (and please note this can also happen with EBS anyway, even if you fsync, and yes, your battery backed cache might fail and this could happen for that reason too!), then on recovery it attempts to join the group again, and it should sync with the leader and receive all missing records? Apologise I am not a raft expert but it's my understand that's what happens.

the problem is what happens if the leader also lose some entries due to the same reason. in a worse situation, for a 3 replica Raft group, if one node loses some entries and two other nodes loses more entries, this will allow those two nodes to rewrite committed logs and cause diverged states on your replicas. 

> Yes there is dataloss, but so what? If the probability of this event happening is less than the probability of underlying storage system failure (e.g. chance of EBS volume loss) it doesn't matter!

Again, if EBS does cause fsynced data to be lost, you shouldn't be using it.

**Comment by purplefox** [comment] 2021-08-17 07:04
> the problem is what happens if the leader also lose some entries due to the same reason. in a worse situation, for a 3 replica Raft group, if one node loses some entries and two other nodes loses more entries, this will allow those two nodes to rewrite committed logs and cause diverged states on your replicas.

Could you explain this scenario in more detail? I'm not sure I understand how it would be possible for this to happen.

**Comment by lni** [comment] 2021-08-18 05:44
Please consider a raft group with 3 nodes, A, B and C. Let's say entries up to index 10 are committed. In case entries after 8 are lost on A while entries after index 5 are lost on B and C. Then B and C can get a set of different entries for entries after index 5, this will cause diverged states for you replicas on those 3 nodes.

**Comment by purplefox** [comment] 2021-08-18 07:51
Can you explain how that would actually happen?

If we do not fsync when we commit every entry, then if a node crashes then it's possible that committed entries aren't in the log of that node. When that node rejoins the quorum it will get sent the missing records. Then the group will be consistent.

If all nodes crash before fsync, then they can all have different numbers of committed entries in their logs. However, entries are only lost from the end of the log (both Pebble and RocksDB ensure logs are not corrupt), so a prefix of the logs of the nodes will be the same. 

AIUI (sorry, I am not a Raft expert!), when the nodes are restarted, leader elections will occur. The node with the largest number of log entries will become leader. The leader will then send AppendEntry requests to followers until all nodes have the same committed log entries. Then all replicas have consistent logs.

So I still cannot see how not fsyncing on every committed record could cause log divergence. Could you elaborate more?

**Comment by purplefox** [comment] 2021-08-19 08:41
@lni Any thoughts on the above?

**Comment by lni** [comment] 2021-08-20 02:19
>If we do not fsync when we commit every entry, then if a node crashes then it's possible that committed entries aren't in the log of that node. When that node rejoins the quorum it will get sent the missing records. Then the group will be consistent.

you can't assume there is no concurrent reboot. please consider the situation in which you have 3 replicas in a data center and a sudden lose of power for the data center.  yes, one can argue that the probability is lower than having a single machine failure, but when it is possible, that is significantly different from not possible at all. with fsync, it is not possible to lose any data even with such concurrent failures. 

without fsync, it would be close to impossible to implement such protocol. whenever a node sends a response indicating an entry has been replicated to it, you'd expect that message to provide certainty that the entry is indeed replicated. without fsync, there is zero real value for such response message, as the remote node sending such message could just reboot and lose that entry at any time. 

same issue for leader election, raft requires the node with the most up to date log entries to be elected as the leader. you won't be able to implement that without fsync, as any node determined to have the most up to date entries can just lose those entries at any time after a reboot.  

another way to look at this issue is to consider what is a reboot. for consensus protocols like paxos/raft, it should really be nothing different from unplug/plug-in your network cable - your machine stops responding to the outside world for a while and then resume in the same state. note that this is not anything unique to dragonboat or raft, it applies to all Paxos variants that I am aware of.  

> If all nodes crash before fsync, then they can all have different numbers of committed entries in their logs. However, entries are only lost from the end of the log (both Pebble and RocksDB ensure logs are not corrupt), so a prefix of the logs of the nodes will be the same.

it is not a problem losing entries that have not been fsynced yet, e.g. follower receives a replicate message that contains some log entries, it writes them to disk and ready to call fsync, if it crashes before fsync is issued and lose all those written but not fsynced entries, it won't cause any trouble for the raft group as no other peer would consider such entries to be replicated (we only let other nodes know that we have such entries after they are fsynced), the end result is nothing different from having the replicate message itself dropped by the network. 

> AIUI (sorry, I am not a Raft expert!), when the nodes are restarted, leader elections will occur. 

only after the crash of the leader node

> The node with the largest number of log entries will become leader. The leader will then send AppendEntry requests to followers until all nodes have the same committed log entries. Then all replicas have consistent logs.

as explained, you can't assume there won't be concurrent failures. by having 3 or 5 replicas, it is all about getting prepared for concurrent failures. fsync is also not just for committed entries, please see the explanation above. 

btw, you also asked why storing raft logs in KV store is wrong. It is because all logs have continuous keys (derived from their continuous indexes), it is wasteful to store such keys when you always continuously access those entries. KV stores like RocksDB/Pebble also use memtables, that means you'd be having an extra copy of the recent raft logs in both RocksDB's wal and in its memtables. 

Please have a look at the following branch, it contains a new LogDB implementation at internal/tan that got the above issues resolved. It is basically Pebble's wal plus extra indexing to allow fast read from the wal.  

https://github.com/lni/dragonboat/tree/experimental

**Comment by purplefox** [comment] 2021-08-20 07:50
Hi @lni it seems you answered a different question. Let's try and keep the discussion focussed :)

**The question was specifically about log divergence, not about data-loss.** I fully understand that dataloss is more likely if we do not fsync committed log entries. I made that clear in the original gitter post.

As I understand it, the Raft protocol ensures that when nodes join the groups (e.g. after failure) they all have the same log entries, so log divergence cannot occur. Yes entries may have been lost but they will all have a consistent view of the log when they are part of the quorum. This is based on an assumption that the underlying log storage (pebble/rocksdb) will only lose data from the end of the logs.

So, it seems any Raft implementation will work fine if fsync is disabled, it's just that the probability of data loss in case of node failure is higher. I.e. not fsyncing on every commit won't break the state machine logic or cause strange failures in dragonboat. (BTW As an example, the new Kafka Raft implementation does not fsync on every write https://cwiki.apache.org/confluence/display/KAFKA/KIP-595%3A+A+Raft+Protocol+for+the+Metadata+Quorum )

Allowing fsync behaviour to be configurable on Dragonboat will not break Dragonboat, it just means the chance of dataloss is higher. So it should be the choice of the user to decide whether they are happy with that chance of dataloss.

**Comment by purplefox** [comment] 2021-08-20 07:55
> with fsync, it is not possible to lose any data even with such concurrent failures.

This is really not true. Although fsync reduces the probability of dataloss, fsynced data can be lost in the real world. The real world is messy, not like an ideal academic thought experiment. Disks fail, battery backed caches fail, SANs fail, fires or tornados happen in data centres. So it really is all about probabilities.

**Comment by purplefox** [comment] 2021-08-20 08:02
Do we agree:

* Probability of dataloss for fsync'd data is low but non zero?
* If we do not fsync on every committed record it won't break dragonboat it will simply increase the probability of dataloss in the case of machine failure?

Based on the above can we agree that it is the choice of the user to decide what probability of dataloss they are comfortable with?

1. If the user wants the highest possible durability guarantee with the loss of some performance, then dragonboat should fsync on every committed record. This should be the default
2. If the user calculates that the probability of dataloss with not fsync is acceptable for their use case, and performance is very important to them, they can disable fsync on every commit. This is not the default.

**Comment by purplefox** [comment] 2021-08-20 08:11
> Please have a look at the following branch, it contains a new LogDB implementation at internal/tan that got the above issues resolved. It is basically Pebble's wal plus extra indexing to allow fast read from the wal.

Very nice! Looking forward to trying this out at some point :)

**Comment by lni** [comment] 2021-08-23 16:26
>The question was specifically about log divergence, not about data-loss.

Please see my answer provided 5 days ago. I copied it below again for your reference. 

>Please consider a raft group with 3 nodes, A, B and C. Let's say entries up to index 10 are committed. In case entries after 8 are lost on A while entries after index 5 are lost on B and C. Then B and C can get a set of different entries for entries after index 5, this will cause diverged states for you replicas on those 3 nodes.

> This is really not true. Although fsync reduces the probability of dataloss, fsynced data can be lost in the real world.

Of course you can lose your data after fsync. I was obviously talking about the fact that you won't lose your writen but not fsynced data simply because of a machine reboot.

> If we do not fsync on every committed record it won't break dragonboat it will simply increase the probability of dataloss in the case of machine failure?

It will completely break the safety guarantees provided by Raft & Paxos. If you are so concerned about the fsync performance and okay with data loss after reboot, why not just go ahead and choose a weaker form of consistency for your system & data?  

> Based on the above can we agree that it is the choice of the user to decide what probability of dataloss they are comfortable with?

Using such logic, one might even argue that it would also be fine to totally skip such disk based storage and store all those raft logs in RAM. With multiple copies of such logs on different machines, it will be highly unlikely to lose all of them at the same time. 

> If the user calculates that the probability of dataloss with not fsync is acceptable for their use case, and performance is very important to them, they can disable fsync on every commit. This is not the default.

If that is the case, why would they bother to have a consensus library such as dragonboat in their system in the first place?

**Comment by purplefox** [comment] 2021-08-24 09:48
> > The question was specifically about log divergence, not about data-loss.
> 
> Please see my answer provided 5 days ago. I copied it below again for your reference.
> 
> > Please consider a raft group with 3 nodes, A, B and C. Let's say entries up to index 10 are committed. In case entries after 8 are lost on A while entries after index 5 are lost on B and C. Then B and C can get a set of different entries for entries after index 5, this will cause diverged states for you replicas on those 3 nodes.

As mentioned previously, it does not appear possible for replicas to have diverged logs when they are in the quorum. The raft protocol ensures that all replicas will have the same log entries. So log divergence does not seem possible.


> 
> > This is really not true. Although fsync reduces the probability of dataloss, fsynced data can be lost in the real world.
> 
> Of course you can lose your data after fsync. I was obviously talking about the fact that you won't lose your writen but not fsynced data simply because of a machine reboot.

If you simply reboot your process before fsyncing you will not lose data. When the node rejoins it will be sent all missing records. Even a hard crash of every process simultaneously won't cause dataloss. Even without fsync, writes in Pebble are written into OS pagecache, and will still be there after process restart. It requires a hard crash simultaneously of all the operating systems that host the processes. This is very unlikely in practice.

As mentioned before many databases and other systems which store critical data rely on the unlikelihood of this to store their data durably. Kafka is one example, MongoDB etc are others. If Kafka fsynced on every write performance would be very, very bad. The level of durability achieved without fsyncing is more than enough for most users.

> 
> > If we do not fsync on every committed record it won't break dragonboat it will simply increase the probability of dataloss in the case of machine failure?
> 
> It will completely break the safety guarantees provided by Raft & Paxos. If you are so concerned about the fsync performance and okay with data loss after reboot, why not just go ahead and choose a weaker form of consistency for your system & data?

The level of durability without fsyncing in a cloud environment is already extremely high. Dataloss can occur whether or not fsyncing occurs. In both cases it is extremely unlikely with the right setup. Raft is also useful for other reasons - concensus serializibility...

> 
> > Based on the above can we agree that it is the choice of the user to decide what probability of dataloss they are comfortable with?
> 
> Using such logic, one might even argue that it would also be fine to totally skip such disk based storage and store all those raft logs in RAM. With multiple copies of such logs on different machines, it will be highly unlikely to lose all of them at the same time.

Yes, and that would be fine too, if the probability of simultaneously failures was sufficiently low. In fact, many companies do exactly this! In memory datagrids are a popular technology and many store critical business data, which is only synced asynchronously to permanent storage. In this case raft is still useful, for replicated state machines - e.g. you wanted to implemented a cluster wide counter or lock.

> 
> > If the user calculates that the probability of dataloss with not fsync is acceptable for their use case, and performance is very important to them, they can disable fsync on every commit. This is not the default.
> 
> If that is the case, why would they bother to have a consensus library such as dragonboat in their system in the first place?

Because a) The probability of dataloss is still extremely low. Most users will never see dataloss whether they fsync or not. and b) as stated above, raft provides many useful things - having consistent state machines is useful for many use cases, even if they are totally in memory.

If Dragon won't provide any easy way to configure fsync, we will need to copy all the internal logDB packages and create our own LogDB implementation that does. Or we will need to fork Dragonboat. We really don't want to do that, but we may have no choice.

As I said before I think Dragonboat is a really great project, please keep up the good work, but please listen to your users, and keep an open mind :)

**Comment by lni** [comment] 2021-08-24 13:57
> As mentioned previously, it does not appear possible for replicas to have diverged logs when they are in the quorum. The raft protocol ensures that all replicas will have the same log entries. So log divergence does not seem possible.

Consider a Raft group with 3 replicas, A, B and C. Let's say the group had two commands committed on log index 1 and 2, they are - 

cmd1, it asks the state machine to do "set x to 1"
cmd2, it asks the state machine to do "set x to 2"

Assuming those log entries are written to disk but not fsynced so some of them can be lost after machine reboot. After machine reboot on B and C, let's say both of them lose the second command, so from their point of view, the only log they have is cmd1 at index 1. Note that the Raft protocol doesn't require the committed index value to be stored. 

Let's say B then win the election with vote from C. B start a proposal for cmd3 which asks the state machine to do "set x to 3", it replicates the cmd to C and thus have it committed at index 2 because from B and C's point of view log entry at index 2 is available. Both of them then get the committed cmd3 applied into the state machine.  ​

Now you have diverged logs on A, B and C, as they have different cmds on log index 2, their state machines are also diverged, A would tell you that x==2, while B and C believes X==3. 

Note that unrelated details (e.g. the noop cmd to be committed after winning the election) are omitted. 

> If Dragon won't provide any easy way to configure fsync, we will need to copy all the internal logDB packages and create our own LogDB implementation that does. Or we will need to fork Dragonboat. We really don't want to do that, but we may have no choice.

Please make sure you don't call that forked dependency dragonboat. 

> please listen to your users, and keep an open mind :)

To totally destroy the reliability and dependability of the library? Thanks, but there is no plan to do that.

**Closed as completed** 2021-08-24 13:59 UTC

**Comment by purplefox** [comment] 2021-08-24 17:14
> > As mentioned previously, it does not appear possible for replicas to have diverged logs when they are in the quorum. The raft protocol ensures that all replicas will have the same log entries. So log divergence does not seem possible.
> 
> Consider a Raft group with 3 replicas, A, B and C. Let's say the group had two commands committed on log index 1 and 2, they are -
> 
> cmd1, it asks the state machine to do "set x to 1"
> cmd2, it asks the state machine to do "set x to 2"
> 
> Assuming those log entries are written to disk but not fsynced so some of them can be lost after machine reboot. After machine reboot on B and C, let's say both of them lose the second command, so from their point of view, the only log they have is cmd1 at index 1. Note that the Raft protocol doesn't require the committed index value to be stored.

I still can't understand how this can happen. Please be patient with me :)

According to the Raft paper:

> In Raft, the leader handles inconsistencies by forcing
> the followers’ logs to duplicate its own. This means that
> conflicting entries in follower logs will be overwritten
> with entries from the leader’s log. Section 5.4 will show
> that this is safe when coupled with one more restriction.
> To bring a follower’s log into consistency with its own,
> the leader must find the latest log entry where the two
> logs agree, delete any entries in the follower’s log after
> that point, and send the follower all of the leader’s entries
> after that point. All of these actions happen in response
> to the consistency check performed by AppendEntries
> RPCs

In the case you describe above A has an extra entry at index 2. When B replicates x = 3 at index 2, A will realise it already has an entry at index 2 and overwrite it, which will bring the logs back into sync. What am I missing here?

**Comment by purplefox** [comment] 2021-08-24 18:33
I discussed this with my colleague, and I think I understand what you're saying now.
Although the raft protocol makes it impossible for the logs to diverge, the *state machines* can diverge. As deleting extra applied entries from the log won't roll-back the statemachine.
But... instead of deleting entries in A from the log couldn't we just apply the last snapshot to it, and replay log entries from there? That way the statemachine would be brought into sync too?

**Comment by lni** [comment] 2021-08-25 07:36
> A will realise it already has an entry at index 2 and overwrite it, which will bring the logs back into sync.

In a 3 replicas group, B and C forms the majority quorum and they are allowed to make all decisions without any involvement of A. That is when a proposal is made from B, B can choose not to replicate the message to A for performance reasons (e.g. latency between A and B is significantly higher than that of B and C), or maybe A is network partitioned and thus couldn't get any message from B and C at all. The most likely case is that B and C simply replies earlier than A, when B gets a response from C, B is allowed to commit the proposals. 

This is enough to cause the log to diverge.

**Comment by purplefox** [comment] 2021-08-25 08:27
I'm not sure I follow this. In your description above, the quorum is still in sync no? Isn't that all that matters? If a node is separated by a network partition, and other nodes still form a quorum, then it's not considered part of the group any more so why do we care what it's log says?

**Comment by lni** [comment] 2021-08-25 10:34
@purplefox when a node is network partitioned, it is still a member of the group.

Please note that this issue is not for raft 101, I'd recommend to read & understand the raft paper first.

**Comment by purplefox** [comment] 2021-08-25 11:22
Thanks I have read the paper.

Firstly the raft paper does not use the term "group" (try searching the Raft paper). It talks about "servers". So, apologies if I cannot read your mind on what you mean by "group". I guess this must be your own terminology.

If the issue is so clear and obvious to you, perhaps you could explain it more clearly.

**Comment by purplefox** [comment] 2021-08-25 11:29
I was trying to say that if a node loses the quorum (e.g. by network partition) then it should not respond to requests any more, so we don't care what's in its log.

If it does rejoin, then, aiui, AppendEntries will be sent to it, and it will delete messages from its log or accept replayed ones until its log is in sync.

In the case that it has too many entries (the Server A example from before), and they have been applied to the state machine, there is a problem, as just deleting entries from the log won't roll back the state machine.

In this case, couldn't Dragonboat just check the last applied index in the statemachine, and if it's already been applied it could either

a) replace it's SM with an earlier snapshot, and delete entries from it's log to the point the snapshot was taken, the leader will then replay missing entries and it will get in sync 
b) refuse to join and shutdown

Either way, the log won't diverge.

Please help me understand why this doesn't work.

**Comment by purplefox** [comment] 2021-08-30 13:29
Hi @lni Any thoughts?
