### ISSUE TITLE
Will snapshot saving leads to election?

### ISSUE THREAD

**Issue by tt67wq** [lni/dragonboat#325] opened 2023-08-31 06:52 UTC
I have a question. I am using a concurrent state machine in my project, and after running steadily for one year, I have observed a phenomenon: every time a snapshot is written to disk, it triggers a leader re-election, as indicated in the logs by the leader losing quorum during snapshot generation. The snapshot data generation in the project holds a lock that blocks other actions of the state machine. I am unsure if this has any impact.

**Comment by lni** [comment] 2023-09-01 02:37
Good to know that it has been running steadily for one year. 

Snapshot creation happens in its own thread, it is completely separated from the threads used for raft protocol execution. There is not much dependencies between the raft protocol (as implemented in dragonboat) and your concurrent state machine (implemented in your code) so I have the feeling that it is unlikely to be caused by some explicitly used locks. 

Could you please provide more details, e.g. the mentioned log, so we can look into this together? In case you don't want to make the log publicly available on the web, please feel free to shoot me an email with the log, my email address is available in those dragonboat source files. Thanks.

**Comment by lni** [comment] 2023-09-01 03:10
Checked code again - I don't see how snapshotting could possibly block the execution of the raft protocol. 

Please prepare a minimum example that can reproduce your claimed issue, you can just make a dummy state machine that sleep certain amount of time to emulate delays required by the I/Os of your snapshot.

**Comment by lni** [comment] 2023-09-11 06:38
@tt67wq would you like to provide a minimum example to reproduce your reported issue?

**Comment by tt67wq** [comment] 2023-09-25 03:46
> @tt67wq would you like to provide a minimum example to reproduce your reported issue?

I‘m trying to make a simpler example cause it's a huge project, give me some time...

**Comment by lni** [comment] 2023-09-25 06:01
@tt67wq 

you can just modify the existing dragonboat-example project available [here](https://github.com/lni/dragonboat-example), a minimum example showing that taking a snapshot can somehow block the execution of the raft protocol and thus causing a election will be enough. you can just sleep some time in the SaveSnapshot() method to emulate certain workload. 

please shot me an email (see source code header for my email address), I can connect you on WeChat and help you to get such an example done.

**Comment by lni** [comment] 2023-10-30 09:50
@tt67wq any progress on reproducing this reported issue? 

I will close it and mark it as "can't reproduce" in a week unless you can share more info.

**Comment by tt67wq** [comment] 2023-11-07 02:10
> @tt67wq any progress on reproducing this reported issue?
> 
> I will close it and mark it as "can't reproduce" in a week unless you can share more info.

OK，If I am able to reproduce it, I will initiate a new issue.

**Comment by lni** [comment] 2023-11-20 13:45
Closed as can't reproduce.

**Closed as completed by lni** 2023-11-20 13:45 UTC
