### ISSUE TITLE
It seems need RocksDB lib when using LevelDB based Raft Log storage

### ISSUE THREAD

**Issue by xianglinghui** [lni/dragonboat#66] opened 2019-06-12 12:40 UTC
Hi，I build my application with LevelDB based Raft Log storage，it reports the follow errors:

[work@tj1-smart-test06 ~/hykv_prj/src/hykv/.gopath/src/hykv]$ go build -v -tags="dragonboat_no_rocksdb" ./cmd/hykv
hykv/vendor/github.com/lni/dragonboat/internal/logdb/kv/rocksdb/gorocksdb
hykv/vendor/github.com/lni/dragonboat/internal/logdb/kv/rocksdb/gorocksdb
vendor/github.com/lni/dragonboat/internal/logdb/kv/rocksdb/gorocksdb/backup.go:5:23: fatal error: rocksdb/c.h: No such file or directory
 #include "rocksdb/c.h"
                       ^
I have set the LogDBFactory field of my config.NodeHostConfig to the factory function leveldb.NewLogDB provided in the github.com/lni/dragonboat/plugin/leveldb package.

**Comment by lni** [comment] 2019-06-12 15:36
Hi @xianglinghui 

Thanks for reporting the issue. 

I had a quick look, the problem is caused by the fact that internal/tests/diskkv.go, internal/tests/diskkv_test.go and nodehost_test.go imported the RocksDB package without taking the dragonboat_no_rocksdb tag into consideration. 

Will fix soon.

**Comment by lni** [comment] 2019-06-13 02:15
Fixed in 544a4b8ff81223ed3705f34d8e2db44e2d252968

The status of the LevelDB support is detailed in docs/storage.md, please make sure to have a look.

**Closed as completed by lni** 2019-06-13 02:15 UTC
