### ISSUE TITLE
check empty im.entries

### ISSUE THREAD

**Issue by DruidCode** [lni/dragonboat#249] opened 2022-08-16 11:32 UTC
```
func (im *inMemory) getEntries(low uint64, high uint64) []pb.Entry {
	upperBound := im.markerIndex + uint64(len(im.entries))
	if low > high || low < im.markerIndex {
		plog.Panicf("invalid low value %d, high %d, marker index %d",
			low, high, im.markerIndex)
	}
	if high > upperBound {
		plog.Panicf("invalid high value %d, upperBound %d", high, upperBound)
	}
	return im.entries[low-im.markerIndex : high-im.markerIndex]
}
```
when progress exists abnormally, like `kill -9`,
then restart, lastIndex lower than appliedIndex
 im.entries empty, throw out panic:
`debug false
panic: runtime error: slice bounds out of range [:1524] with capacity 0`

### Dragonboat version
v3.3.5

### Steps to reproduce the behavior

```
func (im *inMemory) getEntries(low uint64, high uint64) []pb.Entry {
	upperBound := im.markerIndex + uint64(len(im.entries))
	if low > high || low < im.markerIndex {
		plog.Panicf("invalid low value %d, high %d, marker index %d",
			low, high, im.markerIndex)
	}
	if high > upperBound {
		plog.Panicf("invalid high value %d, upperBound %d", high, upperBound)
	}
	if len(im.entries) > 0 {
		return im.entries[low-im.markerIndex : high-im.markerIndex]
	}
	return nil
}
```

**Comment by lni** [comment] 2022-08-16 17:30
Thanks @DruidCode for raising the issue, but I am not sure what lastIndex and appliedIndex variables are you talking about. 

Could you please provide more details? Thanks. 

The stacktrace of your above mentioned panic will also be very useful.

**Comment by DruidCode** [comment] 2022-08-17 02:53
the logs when restart
```
2022-07-27 01:08:30.172100 I | 9474 internal/raft/logentry.go:89 new log entry firstindex: 1861099351, lastIndex: 1862335203
2022-07-27 01:08:30.172111 I | 9474 internal/raft/raft.go:268 [00026:00003] raft log rate limit enabled: true, 1073741824
2022-07-27 01:08:30.172135 I | 9474 internal/raft/raft.go:272 nodestate from snapshot raft state:{4 1 1862335201}, members:{1366099238 map[1:xxxx:18808 3:xxxx:18818 4:xxx:18818 6:xxxx:18823] map[2:true 5:true 7:true 9:true 10:true] map[] map[8:xxx:18810]}
2022-07-27 01:08:30.172181 I | 9474 internal/raft/raft.go:1107 [f:1861099351,l:1862335203,t:4,c:1862335201,a:1861099350] [00026:00003] t4 became follower
2022-07-27 01:08:30.172298 I | 9474 xxxx/node.go:801 [00026:00003] on disk SM is beng initialized
2022-07-27 01:08:30.172348 I | 9474 internal/rsm/adapter.go:291 open read entry index: 1862335965
2022-07-27 01:08:30.172372 I | 9474 internal/rsm/statemachine.go:497 [00026:00003] opened disk SM, index 1862335965
2022-07-27 01:08:30.172385 I | 9474 xxxx/node.go:222 ondiskindex index :1862335965, include log.ondisInitIndex
2022-07-27 01:08:30.172395 I | 9474 internal/raft/peer.go:250 init ondisk index : 1862335965
2022-07-27 01:08:30.172410 I | 9474 internal/rsm/statemachine.go:433 [00026:00003] recovering from <00026:00003:1861099350>, init true, snapshot Imported: %!s(bool=false)
2022-07-27 01:08:30.172439 I | 9474 internal/rsm/statemachine.go:677 4 members included in <00026:00003:1861099350>
2022-07-27 01:08:30.172455 I | 9474 internal/rsm/statemachine.go:679    n00004 : xxx:18818
2022-07-27 01:08:30.172461 I | 9474 internal/rsm/statemachine.go:679    n00006 : xxx:18823
2022-07-27 01:08:30.172468 I | 9474 internal/rsm/statemachine.go:679    n00001 : xxx:18808
2022-07-27 01:08:30.172474 I | 9474 internal/rsm/statemachine.go:679    n00003 : xxx:18818
2022-07-27 01:08:30.172481 I | 9474 internal/rsm/statemachine.go:677 0 nonVotings included in <00026:00003:1861099350>
2022-07-27 01:08:30.172488 I | 9474 internal/rsm/statemachine.go:677 1 witnesses included in <00026:00003:1861099350>
2022-07-27 01:08:30.172494 I | 9474 internal/rsm/statemachine.go:679    n00008 : xxx:18810
2022-07-27 01:08:30.172821 I | 9474 dragonboat/node.go:816 recover snapshot is emtpy : false
2022-07-27 01:08:30.172835 I | 9474 dragonboat/node.go:828 [00026:00003] recovered from <00026:00003:1861099350>
2022-07-27 01:08:30.173321 I | 9474 dragonboat/node.go:1519 processRecoverStatus Task rec.Initial: true, rec.Save:false, rec.Index:1861099350
2022-07-27 01:08:30.173347 I | 9474 dragonboat/node.go:1527 [00026:00003] initialized using <00026:00003:1861099350>
2022-07-27 01:08:30.173357 I | 9474 dragonboat/node.go:1395 [00026:00003] initial index set to 1861099350
2022-07-27 01:08:30.173368 I | 9474 dragonboat/node.go:228 ondiskindex index :1862335965, include statemachine.lastapplied.index, statemachine.index
2022-07-27 01:08:30.173376 I | 9474 internal/rsm/statemachine.go:724 StateMachine SetLastApplied : 1862335965
2022-07-27 01:08:30.365419 I | 9474 dragonboat/node.go:913 [00026:00003] compacted log up to index 1858599350
2022-07-27 01:08:30.365464 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid last applied 1862335965, committed 1862335201) 
2022-07-27 01:08:30.907826 I | 9474 internal/logdb/sharded.go:356 [00026:00003] completed LogDB compaction up to index 1858599350
2022-07-27 01:08:31.393959 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid commitTo index 1862336727, lastIndex() 1862335203)
2022-07-27 01:08:31.394012 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=requested range [1862335966,1862336728) is out of bound [1861099351,1862335203])
2022-07-27 01:08:31.394024 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid high value 1862336728, upperBound 1862335204)
2022-07-27 01:08:32.461039 I | 9603 src/runtime/proc.go:255 xxxx start main exec new server
```



```
debug false
panic: runtime error: slice bounds out of range [:1524] with capacity 0

goroutine 469 [running]:
dragonboat/internal/raft.(*inMemory).getEntries(0xc07c77ed90, 0x6f00fdde, 0x6f0100d8)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/inmemory.go:70 +0x257
dragonboat/internal/raft.(*entryLog).getEntriesFromInMem(0xc000327d20, {0x0, 0x0, 0x0}, 0xc000327d68, 0xc473be)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/logentry.go:215 +0x52
dragonboat/internal/raft.(*entryLog).getEntries(0xc07c77ed80, 0x6f00fdde, 0x6f0100d8, 0x4000000)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/logentry.go:242 +0x85
dragonboat/internal/raft.(*entryLog).getEntriesToApply(0xc07c77ed80, 0x16)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/logentry.go:282 +0x67
dragonboat/internal/raft.(*entryLog).entriesToApply(...)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/logentry.go:277
dragonboat/internal/raft.(*Peer).getUpdate(_, _, _)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/peer.go:354 +0x197
dragonboat/internal/raft.(*Peer).GetUpdate(_, _, _)
        /home/homework/gopath/pkg/mod/dragonboat/internal/raft/peer.go:203 +0x78
dragonboat.(*node).getUpdate(_)
        /home/homework/gopath/pkg/mod/dragonboat/node.go:996 +0x1f7
dragonboat.(*node).stepNode(_)
        /home/homework/gopath/pkg/mod/dragonboat/node.go:1117 +0x178
dragonboat.(*engine).processSteps(0xc03133ad20, 0xc000329df8, 0xc000329e98, 0xc07a0f5710, {0x1d66060, 0x1, 0x0}, 0xc075ffee40)
        /home/homework/gopath/pkg/mod/dragonboat/engine.go:1310 +0x258
dragonboat.(*engine).stepWorkerMain(0xc03133ad20, 0x3)
        /home/homework/gopath/pkg/mod/dragonboat/engine.go:1243 +0x3ec
dragonboat.newExecEngine.func1()
        /home/homework/gopath/pkg/mod/dragonboat/engine.go:1030 +0x68
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1()
        /home/homework/gopath/pkg/mod/github.com/lni/goutils@v1.3.1-0.20210517080819-7f56813dc438/syncutil/stopper.go:79 +0xd2
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
        /home/homework/gopath/pkg/mod/github.com/lni/goutils@v1.3.1-0.20210517080819-7f56813dc438/syncutil/stopper.go:74 +0xef
```

**Comment by lni** [comment] 2022-08-17 06:07
It seems to me that you have a custom logger that doesn't actually do panic. See the above few lines in your logs. It should panic when the invalid last applied value is detected (see the first line below).  

```
9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid last applied 1862335965, committed 1862335201) 
2022-07-27 01:08:30.907826 I | 9474 internal/logdb/sharded.go:356 [00026:00003] completed LogDB compaction up to index 1858599350
2022-07-27 01:08:31.393959 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid commitTo index 1862336727, lastIndex() 1862335203)
2022-07-27 01:08:31.394012 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=requested range [1862335966,1862336728) is out of bound [1861099351,1862335203])
2022-07-27 01:08:31.394024 F | 9474 dragonboat/logger/logger.go:132 fatal%!(EXTRA string=invalid high value 1862336728, upperBound 1862335204)
```

**Comment by lni** [comment] 2022-08-17 06:12
Could you please provide more log, I mean everything produced by your crashed process?

**Comment by lni** [comment] 2022-09-04 14:55
@DruidCode I am still waiting for the above mentioned extra info from you. 

From the limited log you provided, your node has log up to 1862335201, 1862335201 is actually a snapshot. Yet your state machine applied logs up to 1862335965, such a gap is the root cause of the problem you are experience. 

There can be many reasons how this might happen, e.g. your code might incorrectly opened a state machine not really belong to it etc. Please provide extra details on this.

**Comment by lni** [comment] 2022-09-15 07:35
@DruidCode I am going to close this issue, please feel free to re-open once you have the above requested new info.

**Closed as completed by lni** 2022-09-15 07:35 UTC
