### ISSUE TITLE
mem never come down 

### ISSUE THREAD

**Issue by caiwk** [lni/dragonboat#103] opened 2019-10-17 09:09 UTC
every entry is 4M []byte , ondiskStateMachine
while my app is working ,  the mem is growing util 100%. the mem never come down although stop the work of the app, I have to kill the app to release the mem.
this is the mem pprof below,

```
(pprof) top
Showing nodes accounting for 10062.18MB, 99.01% of 10163.01MB total
Dropped 49 nodes (cum <= 50.82MB)
Showing top 10 nodes out of 29
      flat  flat%   sum%        cum   cum%
 8297.58MB 81.64% 81.64%  8297.58MB 81.64%  github.com/lni/dragonboat/v3.prepareProposalPayload
 1026.76MB 10.10% 91.75%  1026.76MB 10.10%  github.com/lni/dragonboat/v3/internal/logdb.newRDBContext
     512MB  5.04% 96.79%      512MB  5.04%  github.com/lni/dragonboat/v3/internal/transport.NewTCPConnection
     204MB  2.01% 98.79%      204MB  2.01%  bytes.makeSlice
   21.34MB  0.21% 99.00%   225.34MB  2.22%  encoding/json.Marshal
    0.50MB 0.0049% 99.01%  8523.92MB 83.87%  main.wwork
         0     0% 99.01%      204MB  2.01%  bytes.(*Buffer).Write
         0     0% 99.01%      204MB  2.01%  bytes.(*Buffer).grow
         0     0% 99.01%      204MB  2.01%  encoding/base64.(*encoder).Write
         0     0% 99.01%      204MB  2.01%  encoding/json.(*encodeState).marshal
(pprof) list github.com/lni/dragonboat/v3.prepareProposalPayload
Total: 9.92GB
ROUTINE ======================== github.com/lni/dragonboat/v3.prepareProposalPayload in /home/test/go/src/cfs/cfs/pkg/mod/github.com/lni/dragonboat/v3@v3.1.3/requests.go
    8.10GB     8.10GB (flat, cum) 81.64% of Total
         .          .   1106:           delete(p.pending, key)
         .          .   1107:   }
         .          .   1108:}
         .          .   1109:
         .          .   1110:func prepareProposalPayload(cmd []byte) []byte {
    8.10GB     8.10GB   1111:   dst := make([]byte, len(cmd))
         .          .   1112:   copy(dst, cmd)
         .          .   1113:   return dst
         .          .   1114:}
(pprof) 
```
it's a bug or something wrong in my code ?

**Comment by lni** [comment] 2019-10-17 09:55
It seems that those 4Mbytes entries were never released - they can't be released until applied into your SM. Please check again to see whether all those proposed entries have been committed & applied. 

Please also note that while entries are expected to stay in RAM until applied, you can use Config. MaxInMemLogSize, NodeHostConfig.MaxSendQueueSize and NodeHostConfig.MaxReceiveQueueSize to control the max RAM size you want to spent on such purposes.

**Comment by caiwk** [comment] 2019-10-17 11:24
I tried to set the Config. MaxInMemLogSize, NodeHostConfig.MaxSendQueueSize and NodeHostConfig.MaxReceiveQueueSize to control the max RAM size,but it doesn't work,the mem still growing...
my code called 				
`
_, err = nh.SyncPropose(ctx, cs, data)
`
if err == nil ,can I consider this entry has been applied into SM?and then `data` will be released?

**Comment by lni** [comment] 2019-10-17 16:41
I have the feeling that I have found the problem. The root causes are in internal/raft/inmemory.go, one of the problems is related to the way how im.entries is resized.

**Comment by caiwk** [comment] 2019-10-19 06:59
actually I have not found the problem , I changed the entry size from 4M to 100k, the mem% could be stable at 14%(64G mem total, 100 multi groups) , I also changed the settings.Soft.InMemEntrySliceSize and settings.Soft.MinEntrySliceFreeSize from 496,96 to 100,50,it seems dosen't work
anyway, I can change the entry size to keep my app working normally

**Comment by caiwk** [comment] 2019-10-19 09:39
I have another problem :
I create 40 raft groups which handle write operation,a rocksdb raft group which record each  write operation

after each write operation, every write-raft-group will call rocksdb.DoOp() in its *OnDiskStateMachine.Update() method to record this op.
```
package rocksdb
func DoOp(nh *dragonboat.NodeHost, cluster uint64, op op, kv KVData) interface{} {
	cs := nh.GetNoOPSession(cluster)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	if op == Put {
		data, err := json.Marshal(kv)
		if err != nil {
			panic(err)
		}
		_, err = nh.SyncPropose(ctx, cs, data)
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "SyncPropose returned error %v\n", err)
		}
	} 
}
```
my code about rocksdb just same as dragonboat-example's ondisk.go

### the problem is 
every write-raft-group blocked in DoOp
`_, err = nh.SyncPropose(ctx, cs, data)`
after 3s ,it timesout ,I try to set timeout to 30s ,it still return after 30s.

I found that diskKV(SM).Update() got nothing and never been called,after calling nh.SyncPropose(ctx, cs, data)

It's strange that if I set numbers of write-raft-group from 40 to 10, everything goes well !!!

**Comment by lni** [comment] 2019-10-23 05:45
@caiwk please open a new issue for the new one.

for the reported memory issue, please provide a minimum program that can re-produce the symptom

**Comment by lni** [comment] 2019-10-23 06:44
@caiwk please also try the release 3.1.3 to see whether you still have the excessive memory usage issue when using 4MBytes entries.

**Comment by lni** [comment] 2019-10-23 15:40
fixed in c9edfab6799c92d4144fa879a65f6ed7e2516265

**Closed as completed by lni** 2019-10-23 15:40 UTC

**Comment by lni** [comment] 2019-10-24 03:35
The issue I described above is not really relevant to the reported symptoms. 

@caiwk please also try the release 3.1.3 to see whether you still have the excessive memory usage issue when using 4MBytes entries, please also provide the detailed steps (e.g. a minimum program) that can reproduce your problem.

**Comment by lni** [comment] 2019-10-26 08:36
The reported issue exists in v3.1.x, it was fixed in the master branch back in July but never got released. v3.1.4 has been released to address this issue.
